from .auth      import router as auth_router
from .users     import router as users_router
from .scans     import router as scans_router
from .voice     import router as voice_router
from .face      import router as face_router
from .nlp       import router as nlp_router
from .fusion    import router as fusion_router
from .alerts    import router as alerts_router
from .export    import router as export_router
from .analytics import router as analytics_router
from .ws        import router as ws_router
